name: Claude Summarize
description: AI-powered build analysis and error diagnosis using Claude
author: https://github.com/mcncl
requirements:
  - bash
  - curl
configuration:
  properties:
    anthropic_base_url:
      type: string
      description: Base URL for Anthropic API
      default: https://api.anthropic.com
    api_key:
      type: string
      description: Anthropic API key for Claude access. Supports environment variables (${VAR}), Buildkite secrets ($(buildkite-agent secret get SECRET)), or direct values
    buildkite_api_token:
      type: string
      description: Buildkite API token for fetching job logs (optional, will use environment BUILDKITE_API_TOKEN if not specified)
    model:
      type: string
      description: Claude model to use
      default: claude-3-7-sonnet-20250219
    trigger:
      type: string
      description: When to trigger Claude analysis
      enum: ["on-failure", "always", "manual"]
      default: on-failure
    analysis_level:
      type: string
      description: Level at which to analyze logs - 'step' for current step only, 'build' for all jobs in the build
      enum: ["step", "build"]
      default: step
    max_log_lines:
      type: integer
      description: Maximum number of log lines to analyze
      default: 1000
    custom_prompt:
      type: string
      description: Custom prompt to append to the analysis request
    timeout:
      type: integer
      description: Timeout in seconds for API requests
      default: 60
    annotate:
      type: boolean
      description: Whether to create build annotations with findings
      default: true
    agent_file:
      type: [boolean, string]
      description: Include agent context file - true for AGENT.md, false to disable, or string path to custom file
      default: false
    compare_builds:
      type: boolean
      description: Enable build time comparison analysis
      default: false
    comparison_range:
      type: integer
      description: Number of previous builds to compare against for build time analysis
      default: 5


  required: [api_key]
  additionalProperties: false
