name: Claude Code
description: AI-powered build analysis and error diagnosis using Claude
author: https://github.com/mcncl
requirements:
  - bash
  - curl
configuration:
  properties:
    api_key:
      type: string
      description: Anthropic API key for Claude access (or use secret_name instead)
    buildkite_api_token:
      type: string
      description: Buildkite API token for fetching job logs (optional, will use environment BUILDKITE_API_TOKEN if not specified)
    model:
      type: string
      description: Claude model to use
      default: claude-3-5-sonnet-20241022
    trigger:
      type: string
      description: When to trigger Claude analysis
      enum: ["on-failure", "always", "manual"]
      default: on-failure
    max_log_lines:
      type: integer
      description: Maximum number of log lines to analyze
      default: 1000
    custom_prompt:
      type: string
      description: Custom prompt to append to the analysis request
    timeout:
      type: integer
      description: Timeout in seconds for API requests
      default: 60
    annotate:
      type: boolean
      description: Whether to create build annotations with findings
      default: true
    suggest_fixes:
      type: boolean
      description: Whether to suggest potential fixes
      default: true
    agent_file:
      type: [boolean, string]
      description: Include agent context file - true for AGENT.md, false to disable, or string path to custom file
      default: false
    secret_name:
      type: string
      description: Name of Buildkite secret containing the Anthropic API key (alternative to api_key)
  oneOf:
    - required: [api_key]
    - required: [secret_name]
  additionalProperties: false
