steps:
  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.4.0:
          files:
            - hooks/**
            - lib/**
            - tests/**

  - label: ":test_tube: Tests"
    plugins:
      - docker-compose#v5.10.0:
          run: tests
          config: compose.yaml

  - label: ":book: Lint"
    plugins:
      - plugin-linter#v3.3.0:
          id: mcncl/claude-code

  - wait: ~

  - label: "🤖 AI Assessment"
    command: |
      echo '🤖 AI Assessment'
    plugins: 
      - secrets#v1.0.0:
          ANTHROPIC_API_KEY: ANTHROPIC_API_KEY
          BUILD_TOKEN: BUILD_TOKEN
      - https://github.com/mcncl/claude-code-buildkite-plugin#main:
          api_key: $$ANTHROPIC_API_KEY
          buildkite_api_token: $$BUILD_TOKEN
          trigger: always
          analysis_level: build
          compare_builds: true
          comparison_range: 5
