env:
  BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH: true

steps:
  - label: ":shell: Tests"
    env:
      BUILDKITE_PLUGIN_CLAUDE_CODE_API_KEY: "$(buildkite-agent secret get ANTHROPIC_API_KEY)"
    plugins:
      - plugin-tester#v1.1.1:
          folders:
            - tests
      - https://github.com/mcncl/claude-code-buildkite-plugin:
          trigger: always

  - label: ":sparkles: Lint"
    plugins:
      - plugin-linter#v3.3.0:
          id: claude-code

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.4.0:
          files:
            - hooks/**
            - lib/**
