env:
  BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH: true

steps:
  - label: ":shell: Tests"
    plugins:
      - plugin-tester#v1.1.1:
          folders:
            - tests
      - secrets#v1.0.0:
          variables:
            CLAUDE_TOKEN: ANTHROPIC_API_KEY 
      - https://github.com/mcncl/claude-code-buildkite-plugin:
          api_key: $$CLAUDE_TOKEN
          trigger: always

  - label: ":sparkles: Lint"
    plugins:
      - plugin-linter#v3.3.0:
          id: claude-code

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.4.0:
          files:
            - hooks/**
            - lib/**
