steps:
  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.4.0:
          files:
            - hooks/**
            - lib/**
            - tests/**

  - label: ":test_tube: Tests"
    plugins:
      - docker-compose#v5.10.0:
          run: tests
          config: compose.yaml

  - label: ":book: Lint"
    plugins:
      - plugin-linter#v3.3.0:
          id: mcncl/claude-code

  - wait: ~

  - label: "🤖 AI Assessment"
    env:
      ANTHROPIC_API_KEY: $(buildkite-agent secret get ANTHROPIC_API_KEY)
      BUILD_TOKEN: $(buildkite-agent secret get BUILD_TOKEN)
    command: |
      echo '🤖 AI Assessment'
    plugins: 
      - https://github.com/mcncl/claude-code-buildkite-plugin#main:
          api_key: "$ANTHROPIC_API_KEY"
          buildkite_api_token: "$BUILD_TOKEN"
          trigger: always
          analysis_level: build
          compare_builds: true
          comparison_range: 5
